### ISSUE TITLE
ImageRecognition - Vertaisarviointi

### ISSUE THREAD

**Issue by ghost** [SimoKorkolainen/ImageRecognition#2]
Koodi on varsin kattavaa, ja yksikkötestaus on toteutettu varsin hyvin muun kodin ohella. Koodin toimintaan en sen enmpää osaa ottaa kantaa. Yksi syy tähän on, että koodi näyttää olevan lähes kauttaaltaan kommentoimatonta, mikä tekee koodin tutkimisesta ulkopuolisen toimesta (ml. allekirjoittanut) paikoitellen todella haasteellista. Mm. metodien toiminnan tarkoitusta ei ole millään lailla tuoda esille. Poikkeuksena ovat functions.activation-paketissa olevat luokat. Jok'ikistä luokkaa en projektista lähtenyt tutkimaan, mutta suuren osan kävin läpi.

Projektin muu dokumentaatio on toteutettu erittäin mallikkaasti ja erityisen informatiivisesti. Tästä peukut.

Terveisin,
Markus

**Comment by SimoKorkolainen** [comment]
Kiitos palautteestasi. Olet oikeassa siitä, että koodin kommentoinnissa olisi parantamisen varaa. Unohdinkin kommentoida koodia viime viikolla. 

Terveisin

Simo
