### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by luluneiti** [SimoKorkolainen/ImageRecognition#3]
15.6.2016, 9.00
- Luokat ja metodit ovat sopivan lyhyitä. Luokkien, attribuuttien ja metodien nimet ovat selkeät. Luokan kuvaus (luokan alussa) helpottaa kokonaisuuden hahmottamista ja metodit dokumentoitu hyvin.
- Luokkia on sen verran paljon, että on hyvä, että ne on jaettu paketteihin. Osassa paketteja on vain 2 luokkaa ja se on minusta liian vähän. 
- Paketteihin jako tuntuu jotenkin "rikkonaiselta". Toisenlaisella paketteihin jaolla voisit helpottaa kokonaisuuden hahmottamista ja korostaa sovelluksen ydintoiminnalisuutta.
- Luokkien suuren määrän takia kannattaa lisätä toteutus-dokumenttiin yleistason luokkakaavio, koska se helpottaa luokkien välisten yhteyksien ja luokkien vastuunjaon hahmottamista.

**Comment by SimoKorkolainen** [comment]
Hei. Kiitos palautteestasi. Olet oikeassa siitä, että pakettijakoa selventämällä ohjelman hahmottaminen helpottuisi. Luokkakaavion lisääminen on hyvä ajatus.

Terveisin

Simo
