### ISSUE TITLE
Please support English Documentation

### ISSUE THREAD

**Issue by ramdrupal7** [SimoKorkolainen/ImageRecognition#4]
Hi Please Support English Documentation so we can find easy to understand your work

**Comment by SimoKorkolainen** [comment]
Hi. 

I'm very pleased that you are interested in my work. My work was made for Helsinki University algorithms course. We were required to write the documentation in Finnish. The code is written in English, but the comments are written in Finnish. 

I'm currently working in the Finnish Defence Forces as a researcher and I don't have very much free time to translate all of the documentation. If you want to ask questions I will answer them and if there is a specific part of the documentation you would like to read in english I can translate it.

Yours sincerely

Simo Korkolainen

**Comment by ramdrupal7** [comment]
Thanks for the Responses simo and i noticed this is Java , but i am looking it for PHP , incase you support PHP We will Take it further and This is My Email Id Ramdrupal7@gmail.com You Can contact me 

Thanks
Ramkumar
